stages:
  - build

variables:
  DOCKER_TLS_CERTDIR: ""
  IMAGE_SHA: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  IMAGE_BRANCH: "$CI_REGISTRY_IMAGE:devops"

build_test_and_push:
  stage: build
  tags:
    - dell-local

  rules:
    - if: '$CI_COMMIT_BRANCH == "devops"'

  before_script:
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin

  script:
    - echo "=== Building Product Service image ==="
    - docker build -t "$IMAGE_SHA" -t "$IMAGE_BRANCH" .

    - echo "=== Testing Product Service container ==="
    - docker run --rm "$IMAGE_SHA" php artisan --version
    - docker run --rm "$IMAGE_SHA" php artisan route:list

    - echo "=== Pushing Product Service image ==="
    - docker push "$IMAGE_SHA"
    - docker push "$IMAGE_BRANCH"

  after_script:
    - docker logout "$CI_REGISTRY" || true