name: Mirror GitHub to GitLab

on:
  push:
  delete:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout complete repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Mirror all branches and tags to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/ecomms1/ecomms-productservice.git

          git push gitlab --all --force
          git push gitlab --tags --force